name: slime
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - jupyter
  - pillow
  - python=3.10.6
  - xeus-python
  - pip
  - pip:
    - numpy
    - matplotlib
    - pandas
    - geopandas
    - networkx
    - scipy
    - empiricaldist
    - requests
    - python-dotenv
