name: slime
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - pillow
  - xeus-python
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - networkx
  - scipy
  - empiricaldist
  - requests
  - python-dotenv
  - tornado
  - pip
  - pip:
      - jupyterlite-core==0.4.1
      - jupyterlab-server>=2.27.1
      - jupyterlite-xeus==2.0.0
      - jupyter-server>=2.4.0
      - jinja2>=3.0.3
      - httpx>=0.25.0
      - packaging
      - async-lru
      - tornado>=6.2.0
      - rtree
